#!/usr/bin/env ruby

require 'json'

string = ARGF.read
string.gsub!(/^[^\(]+\((.+)\);$/, '\1') # if string.end_with? ';'

begin
  puts JSON.pretty_generate(JSON.parse(string))
rescue
  abort("Malformed input.")
end
