#!/usr/bin/env python
import sys
import json


def formatter(j):
    print json.dumps(json.loads(j), sort_keys=True, indent=2)


try:
    fd = sys.stdin
    if (len(sys.argv) == 2):
        fd = open(sys.argv[1])
    with fd as f:
        txt = "".join(f)
    formatter(txt)
except KeyboardInterrupt:
    print ""
    sys.exit(1)
except IOError, e:
    sys.stderr.write("%s\n" % str(e))
    sys.exit(1)
except ValueError:
    '''JSONP?'''
    try:
        txt = txt[txt.index("(")+1:txt.rindex(")")]
        formatter(txt)
    except:
        sys.stderr.write("Malformed input.\n")
        sys.exit(1)
